### ISSUE TITLE
add contribution guidlines

### ISSUE THREAD

**Issue by shivprime94** [shivprime94/Data-Structure-Algorithms#264]

**Comment by Debarpan08** [comment]
Sir, would you please assign this to me?

**Comment by shivprime94** [comment]
@Debarpan08 Go ahead

**Comment by Debarpan08** [comment]
Sir,I'm not able to exactly understand what I need to do,could you please
help me out for once?

**Comment by shivprime94** [comment]
please add a good readme file and look at some youtube video you'll get idea
