### ISSUE TITLE
Best Time to Sell and Buy Stock in Java

### ISSUE THREAD

**Issue by Keerat666** [shivprime94/Data-Structure-Algorithms#279]
I want to contribute a solution for Best Time to Sell and Buy Stock for Leetcode Easy in Java

https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

**Comment by s4shantanu** [comment]
Hey, @shivprime94 Can I contribute to this issue?

**Comment by Keerat666** [comment]
PR raised!

Please let me know if any changes are needed.
