### ISSUE TITLE
Happy to create more issues for other people to contribute.

### ISSUE THREAD

**Issue by Keerat666** [shivprime94/Data-Structure-Algorithms#293]
Please let me know @shivprime94 , if you need me to create more issues and add tasks so that more and more people can contribute.

**Comment by shivprime94** [comment]
shift code files in respective folders

**Comment by Sapna127** [comment]
I would like to work on this issue please assign it to me..

**Comment by Sapna127** [comment]
Need to add Readme file to the repo to make it more readable
