### ISSUE TITLE
Odd Even Linked List

### ISSUE THREAD

**Issue by harshita9621** [shivprime94/Data-Structure-Algorithms#305]
I want to contribute a solution for Odd Even Linked List in C++ for Leetcode Medium

https://leetcode.com/problems/odd-even-linked-list/

**Comment by shivprime94** [comment]
yeah go ahead 😊

**Comment by Arika008** [comment]
Please check my PR #332

**Comment by harshita9621** [comment]
Can I work on this issue

**Comment by harshita9621** [comment]
@shivprime94 Is the repo part of Hacktoberfest

**Comment by shivprime94** [comment]
Yeah, this is part of HF

**Comment by harshita9621** [comment]
Can I work on this issue because issue created by me

**Comment by shivprime94** [comment]
yeah, i have assigned you please make PR
