### ISSUE TITLE
Trapping Rain Water 

### ISSUE THREAD

**Issue by kanikarajpal** [shivprime94/Data-Structure-Algorithms#309]
I would like to add solution to a GFG Problem here.  
The Trapping Rain Water Problem. 

Link - 
https://practice.geeksforgeeks.org/problems/trapping-rain-water-1587115621/0

**Comment by kanikarajpal** [comment]
I have created a pull request, please accept it.
Commit - c03e7ea8e09b48a842494dced0744d685738784e

**Comment by ShreyaShukla03** [comment]
Please check PR #335
