### ISSUE TITLE
Divide Array into Equal Pairs

### ISSUE THREAD

**Issue by deepanshu-rawat6** [shivprime94/Data-Structure-Algorithms#315]
I would like to add a Java code for this problem.

Time Complexity: O(N)
Space Complexity: O(N)

Problem Link: [https://leetcode.com/problems/divide-array-into-equal-pairs/](url)

**Comment by shivprime94** [comment]
Yeah go ahead 😊

**Comment by Arika008** [comment]
Please check my PR #334

**Comment by ShreyaShukla03** [comment]
Please check PR #341 and if found useful please merge it.
