### ISSUE TITLE
Download Speed problem in CSES

### ISSUE THREAD

**Issue by PalaVenkiReddy** [shivprime94/Data-Structure-Algorithms#320]
I want to contribute Download Speed Problem in CSES under Graphs section. Please assign this issue to me.

**Comment by shivprime94** [comment]
Go ahead

**Comment by Debayan97531** [comment]
may i also contribute in this?? @shivprime94

**Comment by Debayan97531** [comment]
I have added one pr...please merge it

**Comment by Debayan97531** [comment]
#340
