### ISSUE TITLE
Tower Of Hanoi

### ISSUE THREAD

**Issue by kanikarajpal** [shivprime94/Data-Structure-Algorithms#349]
I would like to add solution to a GFGProblem here. (C++)
Tower Of Hanoi

Link -
https://practice.geeksforgeeks.org/problems/tower-of-hanoi-1587115621/0

**Comment by kanikarajpal** [comment]
The [tower of Hanoi](https://en.wikipedia.org/wiki/Tower_of_Hanoi) is a famous puzzle where we have three rods and N disks. The objective of the puzzle is to move the entire stack to another rod. You are given the number of discs N. Initially, these discs are in the rod 1. You need to print all the steps of discs movement so that all the discs reach the 3rd rod. Also, you need to find the total moves.
Note: The discs are arranged such that the top disc is numbered 1 and the bottom-most disc is numbered N. Also, all the discs have different sizes and a bigger disc cannot be put on the top of a smaller disc. Refer the provided link to get a better clarity about the puzzle.

**Comment by shivprime94** [comment]
go ahead Kanika 🙂

**Comment by sabhisharma-ise** [comment]
Please assign this issue!
