### ISSUE TITLE
WA Test Cases

### ISSUE THREAD

**Issue by deepanshu-rawat6** [shivprime94/Data-Structure-Algorithms#353]
WA Test Cases (WATESTCASES) under codechef problems 

## Solution

- Language : Cpp
- Time Complexity : $O( n log n )$
- Space Complexity: $O( n )$

Hi @shivprime94 , please assign me this issue.

**Comment by sangalgovind** [comment]
@deepanshu-rawat6 plz assign it to me

**Comment by shivprime94** [comment]
Assigned
