### ISSUE TITLE
Queue to Stack Implementation

### ISSUE THREAD

**Issue by harshita9621** [shivprime94/Data-Structure-Algorithms#369]
Can I work on this issue

**Comment by shivprime94** [comment]
Sure, you go ahead directly without asking

**Comment by Ashpreet-Singh** [comment]
Hey @harshita9621 assign me this task

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me.

**Comment by Hussain6** [comment]
@shivprime94 Can you assign this issue to me I would like to contribute with Queue to Stack implement in cpp.

**Comment by akash-1107** [comment]
Please assign this to me

**Comment by shivprime94** [comment]
@Hussain6 @Ashpreet-Singh @akash-1107 you guys create new issue and work on them. I already assigned this issue to @harshita9621.

**Comment by MrJayendra** [comment]
I am interested in this work 
Please assign it to me
