### ISSUE TITLE
Mail Delivery Problem of CSES

### ISSUE THREAD

**Issue by PalaVenkiReddy** [shivprime94/Data-Structure-Algorithms#375]
I want to contribute to Mail Delivery Problem of CSES under Graphs section. Please assign this issue to me @shivprime94

**Comment by shivprime94** [comment]
Assigned you go ahead

**Comment by Nimesh-21** [comment]
Can I do this too?

**Comment by shivprime94** [comment]
@Nimesh-21 you can create new issues yourself
