### ISSUE TITLE
Rotate matrix by 90 degrees

### ISSUE THREAD

**Issue by nhimanshujain** [shivprime94/Data-Structure-Algorithms#384]
@shivprime94 Can you please assign this issue to me and add Hacktoberfest labels

**Comment by Sakshi2002-Sinha** [comment]
Can you please assign me this issue?

**Comment by shivprime94** [comment]
@Sakshi2002-Sinha please make PR

**Comment by Sakshi2002-Sinha** [comment]
> @Sakshi2002-Sinha please make PR

yeah!
