### ISSUE TITLE
Adding Some famous Graph problems with code

### ISSUE THREAD

**Issue by Shreyash1601** [shivprime94/Data-Structure-Algorithms#422]
I have solved some problems from Love Babbar's DSA sheet and would like to add them

**Comment by Nimesh-21** [comment]
Can you please assign this to me? I am new to open source.

**Comment by Shreyash1601** [comment]
I have already resolved the issue and my PR has been merged. Duplicate PRs
get rejected and disqualified.

Hence I suggest you to feature another issue which could be differentiated
from the one I made
